global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  # consoul for service discover
  - job_name: "pushgateway"
    file_sd_configs:
      - files:
          - "/opt/sh/prometheus/pushgateway.json"
        refresh_interval: 10s
