version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  consoul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    command:
      [
        "consul",
        "agent",
        "-server",
        "-bootstrap",
        "-data-dir",
        "/consul",
        "-ui",
        "-bind",
        "0.0.0.0",
        "-client",
        "0.0.0.0"
      ]

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker/volumes/grafana:/var/lib/grafana
      - ./docker/grafana.ini:/etc/grafana/grafana.ini
