version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./conf/targets.json:/opt/sh/prometheus/pushgateway.json
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
