version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/targets.json:/opt/sh/prometheus/pushgateway.json
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway1
    ports:
      - 9091:9091

  pushgateway2:
    image: prom/pushgateway
    container_name: pushgateway2
    ports:
      - 9092:9091

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker/volumes/grafana:/var/lib/grafana
      - ./docker/grafana.ini:/etc/grafana/grafana.ini
